// /app/layout.tsx (진짜 원본)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"; // AuthProvider만 있어야 합니다.

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* SessionProvider 없이 AuthProvider만 있어야 합니다. */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}